[tool.poetry.group.docker.dependencies]
anyio = "^3.7"
certifi = "^2023.7.22"
cffi = "1.15.1"
charset-normalizer = "2.0.12"
click = "8.0.3"
cryptography = "^41.0.3"
googleapis-common-protos = "^1.60.0"
grpcio = "^1.56.2"
idna = "3.4"
isodate = "0.6.1"
msal = "1.22.0"
msal-extensions = "1.0.0"
msrest = "0.7.1"
oauthlib = "3.2.2"
#polars = {version = "^0.19.12", extras = ["fsspec", "connectorx", "xlsx2csv", "openpyxl", "timezone"]}
portalocker = "2.7.0"
psutil = "5.9.4"
pycparser = "2.21"
pyjwt = "2.6.0"
python-dateutil = "2.8.2"
python-dotenv = "1"
pytz = "2023.3"
requests-oauthlib = "1.3.1"
rfc3986 = "1.5.0"
six = "1.16.0"
sniffio = "1.3.0"
thrift = "0.16.0"
typing-extensions = "4.5.0"
uamqp = "1.6.3"
urllib3 = "1.26.18"